name: release

on:
  push:
    tags:
      - "v*"

jobs:
  push:
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "DRONE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "REPO=ghcr.io/acorn-io" >> $GITHUB_ENV
      - name: Build and push rancher
        run: |
          set -e
          make .dapper
          ./.dapper sh -c './scripts/build && ./scripts/package' || true
          docker push ghcr.io/acorn-io/rancher:$TAG
          docker push ghcr.io/acorn-io/rancher-agent:$TAG
          docker push ghcr.io/acorn-io/rancher-runtime:$TAG
